export const LOAD_INITIAL_SCHOOLS = 'LOAD_INITIAL_SCHOOLS';
export const CREATE_SCHOOL = 'CREATE_SCHOOL';
export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const DESTROY_SCHOOL = 'DESTROY_SCHOOL';

export const LOAD_INITIAL_STUDENTS = 'LOAD_INITIAL_STUDENTS';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DESTROY_STUDENT = 'DESTROY_STUDENT';
